name: assignment-test
on: 
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    unit-test:
        runs-on: self-hosted
        steps:
          - name: Progress
            run: echo ""
    full-test:
        runs-on: self-hosted
        steps:
          - name: Run Full Test
            run: echo ""
