name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # 使用子模組

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

    - name: Build and test
      run: |
        mkdir -p build && cd build
        cmake ..
        make
        ./assignment-autotest/assignment-autotest
name: assignment-test
on: 
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    unit-test:
        container: cuaesd/aesd-autotest:unit-test
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh
      - name: Build and test
        run: |
          mkdir -p build && cd build
          cmake ..
          make
          ./assignment-autotest/assignment-autotest

  unit-test:
    runs-on: self-hosted
    container: cuaesd/aesd-autotest:unit-test
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Run unit test
        run: ./unit-test.sh

  full-test:
    runs-on: self-hosted
    container: cuaesd/aesd-autotest:assignment1
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Run full test
        run: ./full-test.sh
